In [0]:
import numpy as np
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1


array([0, 1, 2, 3, 4, 5])

In [0]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [0]:
  a1.dtype

dtype('int64')

In [0]:
a2.dtype

dtype('float64')

In [0]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [19]:
b2 = np.arange(5)
b2.shape

(5,)

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [31]:
str_a1.dtype

dtype('<U5')

In [32]:
num_a1.dtype

dtype('float64')

In [33]:
np.random.rand(2,3)

array([[0.33395688, 0.95291916, 0.33460222],
       [0.16781829, 0.89652632, 0.85346886]])

In [34]:
np.random.rand()

0.05806377238819327

In [35]:
np.random.rand(2,3,4)

array([[[0.22043467, 0.80004039, 0.33499111, 0.37119895],
        [0.35679519, 0.96110771, 0.70398731, 0.6349718 ],
        [0.18267249, 0.86064044, 0.83606049, 0.93487785]],

       [[0.21652582, 0.307954  , 0.44471405, 0.10597823],
        [0.84791868, 0.4515251 , 0.95522636, 0.48334256],
        [0.17949904, 0.74728143, 0.35356582, 0.12156829]]])

In [36]:
np.random.randint(10, size=(3,4))

array([[7, 1, 9, 0],
       [2, 6, 7, 3],
       [9, 9, 7, 9]])

In [53]:
np.random.randint(1,30)

26